.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. darkpay_qt test_darkpay_qt
clean: FORCE
	$(MAKE) -C .. darkpay_qt_clean test_darkpay_qt_clean
check: FORCE
	$(MAKE) -C .. test_darkpay_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. darkpay_qt
